[3월 15일] 정수론
Altu-Bitu-2/AltuBitu_WJ pull request #4
Opened 2022-03-20 15:48 UTC by wonjinyoo

#### 내용 & 질문
> 2436번은 틀린 코드입니다.. 주석에 내용 적어놓았습니다!

#### <기존 제출>
> 10610, 14490, 2436, 6588

#### <추가 제출>
> X

2022-03-21 01:44 UTC, mkwkw requested changes
선택 3문제 확인되었습니다~ 전체적으로 잘 풀어주셨고 주석도 좋아요!
코멘트 참고하여 수정하시고 re-request review 버튼 눌러주세요~

2022-03-21 01:44 UTC, mkwkw commented on [3월 15일] 정수론/10610.cpp
> +// 만약에 cout<<'-1'; 과 같이 작은 따옴표안에 -1을 넣어 출력하고자 하면 웬 11569라는 숫자가 출력이 된다..
c나 c++에서는 작은 따옴표 안에 단일 기호가 들어가야합니다. '-1'은 -과 1이 결합된 형태이므로 에러가 발생해서 11569라는 비정상적인 값이 출력되는 것입니다.

2022-03-21 01:44 UTC, mkwkw commented on [3월 15일] 정수론/14490.cpp
> +}
유클리드 호제법을 잘 사용하셨습니다!

2022-03-21 01:44 UTC, mkwkw commented on [3월 15일] 정수론/6588.cpp
> +bool findPrime(int n) { // 소수 찾기, 에라토스테네스의 체 활용하고 싶었는데.. 못했습니다ㅠㅠ
p3. 소수인지 아닌지 여부를 저장할 배열을 전역변수로 하나 두고 이 함수를 조금만 변형해서 사용하면 에라토스테네스의 체를 사용할 수 있습니다! 힌트를 드리자면 현재 이 함수의 for문 안에 for문을 하나 더 작성하셔야합니다!

2022-03-21 01:44 UTC, mkwkw commented on [3월 15일] 정수론/2436.cpp
> +}
p1.  두 수 A,B의 최대공약수를 G, 최소공배수를 L이라고 하면
G*L = A*B 가 될 것입니다.
G는 두 수의 최대공약수이므로 A=G*a, B=G*b에요.  따라서 G*L = G*a*G*b입니다. 즉, L/G=a*b가 됩니다.
이것과 A+B=(a+b)*G인 것을 활용하면 문제 해결이 도움이 될 것 같습니다! 시도해보세요~

2022-03-22 12:14 UTC, wonjinyoo commented
피드백 참고하여 2436번 문제 코드 수정하였습니다 감사합니다!

2022-03-22 12:30 UTC, mkwkw approved these changes
수정사항 확인하였습니다~ 머지해주세요~

2022-03-22 13:07 UTC, merged